[git_status]
conflicted = "âš”ï¸ "
ahead = "â¬†ï¸Ã—${count}"
behind = "â¬‡ï¸Ã—${count}"
diverged = "â¬†ï¸Ã—${ahead_count}â¬‡ï¸Ã—${behind_count}"
untracked = "ğŸ†•Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“Ã—${count}"
staged = "ğŸ•ºÃ—${count}"
renamed = "â†”ï¸Ã—${count}"
deleted = "ğŸ—‘ï¸Ã—${count}"
style = "bright-white"
format = "$all_status$ahead_behind"
